### ISSUE TITLE
set separately wallpaper and lock screen wallpaper

### ISSUE THREAD

**Issue by yadeepak** [ajaybhatia/react-native-wallpaper-manager#1]
Hi ,
I tried this plugin to change wallpaper dynamically in my app , but the thing is it changes both wallpaper as well as lock screen , i m just wondering is there any possibility there i can do them individually?

`WallPaperManager.setWallpaper({uri: 'https://www.fillmurray.com/640/360'}, res => alert(res));
`

**Comment by SathishSaminathan** [comment]
Anyone found solution?

**Comment by kmsayem12** [comment]
this issue resolves my side.
https://github.com/ajaybhatia/react-native-wallpaper-manager/pull/3/files

**Comment by yadeepak** [comment]
yes , this needs to be merged

**Comment by ajaybhatia** [comment]
Issue resolved and pull request has been merged https://github.com/ajaybhatia/react-native-wallpaper-manager/commit/080c511562fe347cfbf90ca8a2044e0cbf3c4594

**Comment by SathishSaminathan** [comment]
when will you update the package bro? @ajaybhatia

**Comment by ajaybhatia** [comment]
Updated. Check npmjs.com

**Comment by SathishSaminathan** [comment]
Thanks bro. @ajaybhatia
