### ISSUE TITLE
Main Application Cannot Resolve Symbol

### ISSUE THREAD

**Issue by mikeKane** [ajaybhatia/react-native-wallpaper-manager#2]
Using RN 60.0 I linked as instructed inside of the README and I am receiving this error. 

Cannot find symbol for import com.ajaybhatia.reactnative.wallpaper.WallPaperPackage;

```
info Linking "@ajaybhatia/react-native-wallpaper-manager" Android dependency
info Android module "@ajaybhatia/react-native-wallpaper-manager" has been successfully linked
```

Any ideas?

**Comment by ajaybhatia** [comment]
Hi @mikeKane. From RN > 0.59 you don't need to link. Unlink the library and try to run again.
